-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cordic_base is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    inputData_in_V_read : IN STD_LOGIC_VECTOR (47 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of cordic_base is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv50_0 : STD_LOGIC_VECTOR (49 downto 0) := "00000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv50_1 : STD_LOGIC_VECTOR (49 downto 0) := "00000000000000000000000000000000000000000000000001";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv7_30 : STD_LOGIC_VECTOR (6 downto 0) := "0110000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bit_fu_290_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Result_s_fu_307_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal exitcond_i3_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_327_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_050_6_i_fu_427_p3 : STD_LOGIC_VECTOR (49 downto 0);
    signal exitcond_i_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_fu_482_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_11_fu_452_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_492_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_13_fu_542_p5 : STD_LOGIC_VECTOR (49 downto 0);
    signal p_Result_13_reg_791 : STD_LOGIC_VECTOR (49 downto 0);
    signal j_1_fu_598_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_19_fu_558_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rem_next_V_fu_609_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal rem_next_V_reg_805 : STD_LOGIC_VECTOR (49 downto 0);
    signal p_Result_15_fu_648_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_22_fu_618_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_2_fu_658_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sqrt_int_V_fu_677_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_0289_2_i_fu_687_p3 : STD_LOGIC_VECTOR (49 downto 0);
    signal i_2_fu_693_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal bit_1_fu_709_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal p_Result_4_fu_727_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal exitcond_i6_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_in_V_reg_120 : STD_LOGIC_VECTOR (47 downto 0);
    signal bvh_d_index_reg_132 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_s_reg_143 : STD_LOGIC_VECTOR (49 downto 0);
    signal i1_0_i_reg_155 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_x_outp_V_reg_166 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_0289_0_i_reg_178 : STD_LOGIC_VECTOR (49 downto 0);
    signal i2_0_i_reg_190 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_3_reg_202 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_10_fu_440_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal bvh_d_index_4_reg_212 : STD_LOGIC_VECTOR (5 downto 0);
    signal bvh_d_index_9_reg_223 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_6_reg_234 : STD_LOGIC_VECTOR (24 downto 0);
    signal bvh_d_index_11_reg_244 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_7_reg_255 : STD_LOGIC_VECTOR (24 downto 0);
    signal bvh_d_index_6_reg_266 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Val2_4_fu_110 : STD_LOGIC_VECTOR (49 downto 0);
    signal p_Result_14_fu_588_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal index_assign_11_cast_fu_280_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_296_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_4_fu_303_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bvh_d_index_1_fu_355_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i1_0_i_cast_fu_317_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal bvh_d_index_2_fu_365_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal index_assign_12_cast_fu_371_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_375_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_assign_cast_fu_361_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Repl2_s_fu_383_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_339_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal p_Result_11_fu_397_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal tmp_1_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_10_fu_387_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal sel_tmp_fu_407_p3 : STD_LOGIC_VECTOR (49 downto 0);
    signal bvh_d_index_3_fu_460_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal index_assign_14_cast_fu_448_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_assign_13_cast_fu_466_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Repl2_1_fu_478_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bvh_d_index_7_fu_498_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal bvh_d_index_5_fu_508_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal index_assign_15_cast_fu_514_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal index_assign_16_cast_fu_504_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_518_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_526_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_534_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal bvh_d_index_8_fu_566_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal index_assign_18_cast_fu_554_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_576_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_assign_17_cast_fu_572_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Repl2_2_fu_584_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bvh_d_index_10_fu_626_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal index_assign_20_cast_fu_614_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_636_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_assign_19_cast_fu_632_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Repl2_3_fu_644_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_23_fu_664_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_Result_s_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal index_assign_21_cast_fu_699_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_715_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_5_fu_723_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv25_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = exitcond_i6_fu_703_p2))) then 
                    ap_return_preg <= p_Val2_7_reg_255;
                end if; 
            end if;
        end if;
    end process;


    bvh_d_index_11_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_0 = tmp_22_fu_618_p3))) then 
                bvh_d_index_11_reg_244 <= j_2_fu_658_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = tmp_19_fu_558_p3))) then 
                bvh_d_index_11_reg_244 <= ap_const_lv6_17;
            end if; 
        end if;
    end process;

    bvh_d_index_4_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_0 = tmp_11_fu_452_p3))) then 
                bvh_d_index_4_reg_212 <= j_fu_492_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_0 = tmp_10_fu_440_p3))) then 
                bvh_d_index_4_reg_212 <= ap_const_lv6_17;
            end if; 
        end if;
    end process;

    bvh_d_index_6_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = tmp_10_fu_440_p3))) then 
                bvh_d_index_6_reg_266 <= ap_const_lv5_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_0 = exitcond_i6_fu_703_p2))) then 
                bvh_d_index_6_reg_266 <= bit_1_fu_709_p2;
            end if; 
        end if;
    end process;

    bvh_d_index_9_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_0 = tmp_19_fu_558_p3))) then 
                bvh_d_index_9_reg_223 <= j_1_fu_598_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_11_fu_452_p3 = ap_const_lv1_1))) then 
                bvh_d_index_9_reg_223 <= ap_const_lv6_16;
            end if; 
        end if;
    end process;

    bvh_d_index_reg_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_i3_fu_284_p2 = ap_const_lv1_0))) then 
                bvh_d_index_reg_132 <= bit_fu_290_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                bvh_d_index_reg_132 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    data_x_outp_V_reg_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_i_fu_321_p2 = ap_const_lv1_1))) then 
                data_x_outp_V_reg_166 <= ap_const_lv25_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = tmp_22_fu_618_p3))) then 
                data_x_outp_V_reg_166 <= sqrt_int_V_fu_677_p4;
            end if; 
        end if;
    end process;

    i1_0_i_reg_155_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_i3_fu_284_p2 = ap_const_lv1_1))) then 
                i1_0_i_reg_155 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_0 = exitcond_i_fu_321_p2))) then 
                i1_0_i_reg_155 <= i_fu_327_p2;
            end if; 
        end if;
    end process;

    i2_0_i_reg_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_i_fu_321_p2 = ap_const_lv1_1))) then 
                i2_0_i_reg_190 <= ap_const_lv6_18;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = tmp_22_fu_618_p3))) then 
                i2_0_i_reg_190 <= i_2_fu_693_p2;
            end if; 
        end if;
    end process;

    p_0289_0_i_reg_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_i_fu_321_p2 = ap_const_lv1_1))) then 
                p_0289_0_i_reg_178 <= ap_const_lv50_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = tmp_22_fu_618_p3))) then 
                p_0289_0_i_reg_178 <= p_0289_2_i_fu_687_p3;
            end if; 
        end if;
    end process;

    p_Val2_3_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_lv1_0 = tmp_11_fu_452_p3))) then 
                p_Val2_3_reg_202 <= p_Result_12_fu_482_p4;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_0 = tmp_10_fu_440_p3))) then 
                p_Val2_3_reg_202 <= p_0289_0_i_reg_178;
            end if; 
        end if;
    end process;

    p_Val2_4_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_0 = tmp_19_fu_558_p3))) then 
                p_Val2_4_fu_110 <= p_Result_14_fu_588_p4;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_i_fu_321_p2 = ap_const_lv1_1))) then 
                p_Val2_4_fu_110 <= ap_const_lv50_1;
            end if; 
        end if;
    end process;

    p_Val2_6_reg_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_0 = tmp_22_fu_618_p3))) then 
                p_Val2_6_reg_234 <= p_Result_15_fu_648_p4;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = tmp_19_fu_558_p3))) then 
                p_Val2_6_reg_234 <= data_x_outp_V_reg_166;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_11_fu_452_p3 = ap_const_lv1_1))) then
                p_Result_13_reg_791 <= p_Result_13_fu_542_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_0 = exitcond_i6_fu_703_p2))) then
                p_Val2_7_reg_255 <= p_Result_4_fu_727_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_0 = exitcond_i_fu_321_p2))) then
                p_Val2_s_reg_143 <= p_050_6_i_fu_427_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = tmp_19_fu_558_p3))) then
                rem_next_V_reg_805 <= rem_next_V_fu_609_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_i3_fu_284_p2 = ap_const_lv1_0))) then
                x_in_V_reg_120 <= p_Result_s_fu_307_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_i3_fu_284_p2, ap_CS_fsm_state3, exitcond_i_fu_321_p2, ap_CS_fsm_state5, tmp_11_fu_452_p3, ap_CS_fsm_state6, tmp_19_fu_558_p3, ap_CS_fsm_state7, tmp_22_fu_618_p3, ap_CS_fsm_state8, exitcond_i6_fu_703_p2, ap_CS_fsm_state4, tmp_10_fu_440_p3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_i3_fu_284_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond_i_fu_321_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_lv1_1 = tmp_10_fu_440_p3))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (tmp_11_fu_452_p3 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_lv1_1 = tmp_19_fu_558_p3))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (ap_const_lv1_1 = tmp_22_fu_618_p3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = exitcond_i6_fu_703_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8, exitcond_i6_fu_703_p2)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = exitcond_i6_fu_703_p2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, exitcond_i6_fu_703_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = exitcond_i6_fu_703_p2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state8, exitcond_i6_fu_703_p2, p_Val2_7_reg_255, ap_return_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = exitcond_i6_fu_703_p2))) then 
            ap_return <= p_Val2_7_reg_255;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    bit_1_fu_709_p2 <= std_logic_vector(unsigned(bvh_d_index_6_reg_266) + unsigned(ap_const_lv5_1));
    bit_fu_290_p2 <= std_logic_vector(unsigned(bvh_d_index_reg_132) + unsigned(ap_const_lv6_1));
    bvh_d_index_10_fu_626_p2 <= std_logic_vector(unsigned(bvh_d_index_11_reg_244) + unsigned(ap_const_lv6_1));
    bvh_d_index_1_fu_355_p2 <= std_logic_vector(signed(ap_const_lv6_31) - signed(i1_0_i_reg_155));
    bvh_d_index_2_fu_365_p2 <= std_logic_vector(unsigned(ap_const_lv7_30) - unsigned(i1_0_i_cast_fu_317_p1));
    bvh_d_index_3_fu_460_p2 <= std_logic_vector(unsigned(bvh_d_index_4_reg_212) + unsigned(ap_const_lv6_2));
    bvh_d_index_5_fu_508_p2 <= (bvh_d_index_7_fu_498_p2 or ap_const_lv6_1);
    bvh_d_index_7_fu_498_p2 <= std_logic_vector(shift_left(unsigned(i2_0_i_reg_190),to_integer(unsigned('0' & ap_const_lv6_1(6-1 downto 0)))));
    bvh_d_index_8_fu_566_p2 <= std_logic_vector(unsigned(bvh_d_index_9_reg_223) + unsigned(ap_const_lv6_2));
    exitcond_i3_fu_284_p2 <= "1" when (bvh_d_index_reg_132 = ap_const_lv6_30) else "0";
    exitcond_i6_fu_703_p2 <= "1" when (bvh_d_index_6_reg_266 = ap_const_lv5_19) else "0";
    exitcond_i_fu_321_p2 <= "1" when (i1_0_i_reg_155 = ap_const_lv6_32) else "0";
    i1_0_i_cast_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i1_0_i_reg_155),7));
    i_2_fu_693_p2 <= std_logic_vector(unsigned(i2_0_i_reg_190) + unsigned(ap_const_lv6_3F));
    i_fu_327_p2 <= std_logic_vector(unsigned(i1_0_i_reg_155) + unsigned(ap_const_lv6_1));
    index_assign_11_cast_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_reg_132),32));
        index_assign_12_cast_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bvh_d_index_2_fu_365_p2),32));

    index_assign_13_cast_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_3_fu_460_p2),32));
        index_assign_14_cast_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bvh_d_index_4_reg_212),32));

    index_assign_15_cast_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_5_fu_508_p2),32));
    index_assign_16_cast_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_7_fu_498_p2),32));
    index_assign_17_cast_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_8_fu_566_p2),32));
        index_assign_18_cast_fu_554_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bvh_d_index_9_reg_223),32));

    index_assign_19_cast_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_10_fu_626_p2),32));
        index_assign_20_cast_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bvh_d_index_11_reg_244),32));

    index_assign_21_cast_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_6_reg_266),32));
    index_assign_cast_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bvh_d_index_1_fu_355_p2),32));
    j_1_fu_598_p2 <= std_logic_vector(unsigned(bvh_d_index_9_reg_223) + unsigned(ap_const_lv6_3F));
    j_2_fu_658_p2 <= std_logic_vector(unsigned(bvh_d_index_11_reg_244) + unsigned(ap_const_lv6_3F));
    j_fu_492_p2 <= std_logic_vector(unsigned(bvh_d_index_4_reg_212) + unsigned(ap_const_lv6_3F));
    not_Result_s_fu_671_p2 <= (tmp_23_fu_664_p3 xor ap_const_lv1_1);
    p_0289_2_i_fu_687_p3 <= 
        p_Result_13_reg_791 when (tmp_23_fu_664_p3(0) = '1') else 
        rem_next_V_reg_805;
    p_050_6_i_fu_427_p3 <= 
        p_Result_10_fu_387_p4 when (sel_tmp2_fu_421_p2(0) = '1') else 
        sel_tmp_fu_407_p3;
    p_Repl2_1_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_fu_470_p3),64));
    p_Repl2_2_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_576_p3),64));
    p_Repl2_3_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_636_p3),64));
    p_Repl2_4_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_296_p3),64));
    p_Repl2_5_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_715_p3),64));
    p_Repl2_s_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_375_p3),64));
    
    p_Result_10_fu_387_p4_proc : process(p_Val2_s_reg_143, index_assign_cast_fu_361_p1, p_Repl2_s_fu_383_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_10_fu_387_p4 <= p_Val2_s_reg_143;
        if to_integer(unsigned(index_assign_cast_fu_361_p1)) >= p_Val2_s_reg_143'low and to_integer(unsigned(index_assign_cast_fu_361_p1)) <= p_Val2_s_reg_143'high then
            result(0) := '0';
            for i in p_Repl2_s_fu_383_p1'range loop
                result(0) := result(0) or p_Repl2_s_fu_383_p1(i);
            end loop;
            p_Result_10_fu_387_p4(to_integer(unsigned(index_assign_cast_fu_361_p1))) <= result(0);
        end if;
    end process;

    
    p_Result_11_fu_397_p4_proc : process(p_Val2_s_reg_143, index_assign_cast_fu_361_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_11_fu_397_p4 <= p_Val2_s_reg_143;
        if to_integer(unsigned(index_assign_cast_fu_361_p1)) >= p_Val2_s_reg_143'low and to_integer(unsigned(index_assign_cast_fu_361_p1)) <= p_Val2_s_reg_143'high then
            result(0) := '0';
            for i in ap_const_lv64_0'range loop
                result(0) := result(0) or ap_const_lv64_0(i);
            end loop;
            p_Result_11_fu_397_p4(to_integer(unsigned(index_assign_cast_fu_361_p1))) <= result(0);
        end if;
    end process;

    
    p_Result_12_fu_482_p4_proc : process(p_Val2_3_reg_202, index_assign_13_cast_fu_466_p1, p_Repl2_1_fu_478_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_12_fu_482_p4 <= p_Val2_3_reg_202;
        if to_integer(unsigned(index_assign_13_cast_fu_466_p1)) >= p_Val2_3_reg_202'low and to_integer(unsigned(index_assign_13_cast_fu_466_p1)) <= p_Val2_3_reg_202'high then
            result(0) := '0';
            for i in p_Repl2_1_fu_478_p1'range loop
                result(0) := result(0) or p_Repl2_1_fu_478_p1(i);
            end loop;
            p_Result_12_fu_482_p4(to_integer(unsigned(index_assign_13_cast_fu_466_p1))) <= result(0);
        end if;
    end process;

    p_Result_13_fu_542_p5 <= (p_Val2_3_reg_202(49 downto 2) & tmp_6_fu_534_p3);
    
    p_Result_14_fu_588_p4_proc : process(p_Val2_4_fu_110, index_assign_17_cast_fu_572_p1, p_Repl2_2_fu_584_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_14_fu_588_p4 <= p_Val2_4_fu_110;
        if to_integer(unsigned(index_assign_17_cast_fu_572_p1)) >= p_Val2_4_fu_110'low and to_integer(unsigned(index_assign_17_cast_fu_572_p1)) <= p_Val2_4_fu_110'high then
            result(0) := '0';
            for i in p_Repl2_2_fu_584_p1'range loop
                result(0) := result(0) or p_Repl2_2_fu_584_p1(i);
            end loop;
            p_Result_14_fu_588_p4(to_integer(unsigned(index_assign_17_cast_fu_572_p1))) <= result(0);
        end if;
    end process;

    
    p_Result_15_fu_648_p4_proc : process(p_Val2_6_reg_234, index_assign_19_cast_fu_632_p1, p_Repl2_3_fu_644_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_15_fu_648_p4 <= p_Val2_6_reg_234;
        if to_integer(unsigned(index_assign_19_cast_fu_632_p1)) >= p_Val2_6_reg_234'low and to_integer(unsigned(index_assign_19_cast_fu_632_p1)) <= p_Val2_6_reg_234'high then
            result(0) := '0';
            for i in p_Repl2_3_fu_644_p1'range loop
                result(0) := result(0) or p_Repl2_3_fu_644_p1(i);
            end loop;
            p_Result_15_fu_648_p4(to_integer(unsigned(index_assign_19_cast_fu_632_p1))) <= result(0);
        end if;
    end process;

    
    p_Result_4_fu_727_p4_proc : process(p_Val2_7_reg_255, index_assign_21_cast_fu_699_p1, p_Repl2_5_fu_723_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_4_fu_727_p4 <= p_Val2_7_reg_255;
        if to_integer(unsigned(index_assign_21_cast_fu_699_p1)) >= p_Val2_7_reg_255'low and to_integer(unsigned(index_assign_21_cast_fu_699_p1)) <= p_Val2_7_reg_255'high then
            result(0) := '0';
            for i in p_Repl2_5_fu_723_p1'range loop
                result(0) := result(0) or p_Repl2_5_fu_723_p1(i);
            end loop;
            p_Result_4_fu_727_p4(to_integer(unsigned(index_assign_21_cast_fu_699_p1))) <= result(0);
        end if;
    end process;

    
    p_Result_9_fu_339_p4_proc : process(p_Val2_s_reg_143)
    begin
        p_Result_9_fu_339_p4 <= p_Val2_s_reg_143;
        p_Result_9_fu_339_p4(49) <= ap_const_lv1_0(0);
    end process;

    
    p_Result_s_fu_307_p4_proc : process(x_in_V_reg_120, index_assign_11_cast_fu_280_p1, p_Repl2_4_fu_303_p1)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_s_fu_307_p4 <= x_in_V_reg_120;
        if to_integer(unsigned(index_assign_11_cast_fu_280_p1)) >= x_in_V_reg_120'low and to_integer(unsigned(index_assign_11_cast_fu_280_p1)) <= x_in_V_reg_120'high then
            result(0) := '0';
            for i in p_Repl2_4_fu_303_p1'range loop
                result(0) := result(0) or p_Repl2_4_fu_303_p1(i);
            end loop;
            p_Result_s_fu_307_p4(to_integer(unsigned(index_assign_11_cast_fu_280_p1))) <= result(0);
        end if;
    end process;

    rem_next_V_fu_609_p2 <= std_logic_vector(unsigned(p_Result_13_reg_791) - unsigned(p_Val2_4_fu_110));
    sel_tmp1_fu_415_p2 <= (tmp_fu_333_p2 xor ap_const_lv1_1);
    sel_tmp2_fu_421_p2 <= (tmp_1_fu_349_p2 and sel_tmp1_fu_415_p2);
    sel_tmp_fu_407_p3 <= 
        p_Result_9_fu_339_p4 when (tmp_fu_333_p2(0) = '1') else 
        p_Result_11_fu_397_p4;
    
    sqrt_int_V_fu_677_p4_proc : process(p_Val2_6_reg_234, not_Result_s_fu_671_p2)
    begin
        sqrt_int_V_fu_677_p4 <= p_Val2_6_reg_234;
        sqrt_int_V_fu_677_p4(0) <= not_Result_s_fu_671_p2(0);
    end process;

    tmp_10_fu_440_p3 <= i2_0_i_reg_190(5 downto 5);
    tmp_11_fu_452_p3 <= bvh_d_index_4_reg_212(5 downto 5);
    tmp_12_fu_715_p3 <= data_x_outp_V_reg_166(to_integer(unsigned(index_assign_21_cast_fu_699_p1)) downto to_integer(unsigned(index_assign_21_cast_fu_699_p1))) when (to_integer(unsigned(index_assign_21_cast_fu_699_p1))>= 0 and to_integer(unsigned(index_assign_21_cast_fu_699_p1))<=24) else "-";
    tmp_15_fu_518_p3 <= p_Val2_s_reg_143(to_integer(unsigned(index_assign_15_cast_fu_514_p1)) downto to_integer(unsigned(index_assign_15_cast_fu_514_p1))) when (to_integer(unsigned(index_assign_15_cast_fu_514_p1))>= 0 and to_integer(unsigned(index_assign_15_cast_fu_514_p1))<=49) else "-";
    tmp_16_fu_526_p3 <= p_Val2_s_reg_143(to_integer(unsigned(index_assign_16_cast_fu_504_p1)) downto to_integer(unsigned(index_assign_16_cast_fu_504_p1))) when (to_integer(unsigned(index_assign_16_cast_fu_504_p1))>= 0 and to_integer(unsigned(index_assign_16_cast_fu_504_p1))<=49) else "-";
    tmp_17_fu_470_p3 <= p_Val2_3_reg_202(to_integer(unsigned(index_assign_14_cast_fu_448_p1)) downto to_integer(unsigned(index_assign_14_cast_fu_448_p1))) when (to_integer(unsigned(index_assign_14_cast_fu_448_p1))>= 0 and to_integer(unsigned(index_assign_14_cast_fu_448_p1))<=49) else "-";
    tmp_19_fu_558_p3 <= bvh_d_index_9_reg_223(5 downto 5);
    tmp_1_fu_349_p2 <= "1" when (unsigned(i1_0_i_reg_155) < unsigned(ap_const_lv6_31)) else "0";
    tmp_20_fu_576_p3 <= data_x_outp_V_reg_166(to_integer(unsigned(index_assign_18_cast_fu_554_p1)) downto to_integer(unsigned(index_assign_18_cast_fu_554_p1))) when (to_integer(unsigned(index_assign_18_cast_fu_554_p1))>= 0 and to_integer(unsigned(index_assign_18_cast_fu_554_p1))<=24) else "-";
    tmp_22_fu_618_p3 <= bvh_d_index_11_reg_244(5 downto 5);
    tmp_23_fu_664_p3 <= rem_next_V_reg_805(25 downto 25);
    tmp_25_fu_636_p3 <= p_Val2_6_reg_234(to_integer(unsigned(index_assign_20_cast_fu_614_p1)) downto to_integer(unsigned(index_assign_20_cast_fu_614_p1))) when (to_integer(unsigned(index_assign_20_cast_fu_614_p1))>= 0 and to_integer(unsigned(index_assign_20_cast_fu_614_p1))<=24) else "-";
    tmp_2_fu_296_p3 <= inputData_in_V_read(to_integer(unsigned(index_assign_11_cast_fu_280_p1)) downto to_integer(unsigned(index_assign_11_cast_fu_280_p1))) when (to_integer(unsigned(index_assign_11_cast_fu_280_p1))>= 0 and to_integer(unsigned(index_assign_11_cast_fu_280_p1))<=47) else "-";
    tmp_6_fu_534_p3 <= (tmp_15_fu_518_p3 & tmp_16_fu_526_p3);
    tmp_7_fu_375_p3 <= x_in_V_reg_120(to_integer(unsigned(index_assign_12_cast_fu_371_p1)) downto to_integer(unsigned(index_assign_12_cast_fu_371_p1))) when (to_integer(unsigned(index_assign_12_cast_fu_371_p1))>= 0 and to_integer(unsigned(index_assign_12_cast_fu_371_p1))<=47) else "-";
    tmp_fu_333_p2 <= "1" when (i1_0_i_reg_155 = ap_const_lv6_0) else "0";
end behav;
