// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cordic_base.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cordic_base::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cordic_base::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> cordic_base::ap_ST_fsm_state1 = "1";
const sc_lv<8> cordic_base::ap_ST_fsm_state2 = "10";
const sc_lv<8> cordic_base::ap_ST_fsm_state3 = "100";
const sc_lv<8> cordic_base::ap_ST_fsm_state4 = "1000";
const sc_lv<8> cordic_base::ap_ST_fsm_state5 = "10000";
const sc_lv<8> cordic_base::ap_ST_fsm_state6 = "100000";
const sc_lv<8> cordic_base::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> cordic_base::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> cordic_base::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cordic_base::ap_const_lv32_1 = "1";
const sc_lv<1> cordic_base::ap_const_lv1_0 = "0";
const sc_lv<32> cordic_base::ap_const_lv32_2 = "10";
const sc_lv<32> cordic_base::ap_const_lv32_4 = "100";
const sc_lv<1> cordic_base::ap_const_lv1_1 = "1";
const sc_lv<32> cordic_base::ap_const_lv32_5 = "101";
const sc_lv<32> cordic_base::ap_const_lv32_6 = "110";
const sc_lv<32> cordic_base::ap_const_lv32_7 = "111";
const sc_lv<6> cordic_base::ap_const_lv6_0 = "000000";
const sc_lv<25> cordic_base::ap_const_lv25_0 = "0000000000000000000000000";
const sc_lv<50> cordic_base::ap_const_lv50_0 = "00000000000000000000000000000000000000000000000000";
const sc_lv<6> cordic_base::ap_const_lv6_18 = "11000";
const sc_lv<32> cordic_base::ap_const_lv32_3 = "11";
const sc_lv<6> cordic_base::ap_const_lv6_17 = "10111";
const sc_lv<6> cordic_base::ap_const_lv6_16 = "10110";
const sc_lv<5> cordic_base::ap_const_lv5_0 = "00000";
const sc_lv<50> cordic_base::ap_const_lv50_1 = "1";
const sc_lv<6> cordic_base::ap_const_lv6_30 = "110000";
const sc_lv<6> cordic_base::ap_const_lv6_1 = "1";
const sc_lv<6> cordic_base::ap_const_lv6_32 = "110010";
const sc_lv<32> cordic_base::ap_const_lv32_31 = "110001";
const sc_lv<6> cordic_base::ap_const_lv6_31 = "110001";
const sc_lv<7> cordic_base::ap_const_lv7_30 = "110000";
const sc_lv<64> cordic_base::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<6> cordic_base::ap_const_lv6_2 = "10";
const sc_lv<6> cordic_base::ap_const_lv6_3F = "111111";
const sc_lv<32> cordic_base::ap_const_lv32_19 = "11001";
const sc_lv<5> cordic_base::ap_const_lv5_19 = "11001";
const sc_lv<5> cordic_base::ap_const_lv5_1 = "1";
const bool cordic_base::ap_const_boolean_1 = true;

cordic_base::cordic_base(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_i6_fu_703_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_i6_fu_703_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_i6_fu_703_p2 );
    sensitive << ( p_Val2_7_reg_255 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_bit_1_fu_709_p2);
    sensitive << ( bvh_d_index_6_reg_266 );

    SC_METHOD(thread_bit_fu_290_p2);
    sensitive << ( bvh_d_index_reg_132 );

    SC_METHOD(thread_bvh_d_index_10_fu_626_p2);
    sensitive << ( bvh_d_index_11_reg_244 );

    SC_METHOD(thread_bvh_d_index_1_fu_355_p2);
    sensitive << ( i1_0_i_reg_155 );

    SC_METHOD(thread_bvh_d_index_2_fu_365_p2);
    sensitive << ( i1_0_i_cast_fu_317_p1 );

    SC_METHOD(thread_bvh_d_index_3_fu_460_p2);
    sensitive << ( bvh_d_index_4_reg_212 );

    SC_METHOD(thread_bvh_d_index_5_fu_508_p2);
    sensitive << ( bvh_d_index_7_fu_498_p2 );

    SC_METHOD(thread_bvh_d_index_7_fu_498_p2);
    sensitive << ( i2_0_i_reg_190 );

    SC_METHOD(thread_bvh_d_index_8_fu_566_p2);
    sensitive << ( bvh_d_index_9_reg_223 );

    SC_METHOD(thread_exitcond_i3_fu_284_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( bvh_d_index_reg_132 );

    SC_METHOD(thread_exitcond_i6_fu_703_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( bvh_d_index_6_reg_266 );

    SC_METHOD(thread_exitcond_i_fu_321_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i1_0_i_reg_155 );

    SC_METHOD(thread_i1_0_i_cast_fu_317_p1);
    sensitive << ( i1_0_i_reg_155 );

    SC_METHOD(thread_i_2_fu_693_p2);
    sensitive << ( i2_0_i_reg_190 );

    SC_METHOD(thread_i_fu_327_p2);
    sensitive << ( i1_0_i_reg_155 );

    SC_METHOD(thread_index_assign_11_cast_fu_280_p1);
    sensitive << ( bvh_d_index_reg_132 );

    SC_METHOD(thread_index_assign_12_cast_fu_371_p1);
    sensitive << ( bvh_d_index_2_fu_365_p2 );

    SC_METHOD(thread_index_assign_13_cast_fu_466_p1);
    sensitive << ( bvh_d_index_3_fu_460_p2 );

    SC_METHOD(thread_index_assign_14_cast_fu_448_p1);
    sensitive << ( bvh_d_index_4_reg_212 );

    SC_METHOD(thread_index_assign_15_cast_fu_514_p1);
    sensitive << ( bvh_d_index_5_fu_508_p2 );

    SC_METHOD(thread_index_assign_16_cast_fu_504_p1);
    sensitive << ( bvh_d_index_7_fu_498_p2 );

    SC_METHOD(thread_index_assign_17_cast_fu_572_p1);
    sensitive << ( bvh_d_index_8_fu_566_p2 );

    SC_METHOD(thread_index_assign_18_cast_fu_554_p1);
    sensitive << ( bvh_d_index_9_reg_223 );

    SC_METHOD(thread_index_assign_19_cast_fu_632_p1);
    sensitive << ( bvh_d_index_10_fu_626_p2 );

    SC_METHOD(thread_index_assign_20_cast_fu_614_p1);
    sensitive << ( bvh_d_index_11_reg_244 );

    SC_METHOD(thread_index_assign_21_cast_fu_699_p1);
    sensitive << ( bvh_d_index_6_reg_266 );

    SC_METHOD(thread_index_assign_cast_fu_361_p1);
    sensitive << ( bvh_d_index_1_fu_355_p2 );

    SC_METHOD(thread_j_1_fu_598_p2);
    sensitive << ( bvh_d_index_9_reg_223 );

    SC_METHOD(thread_j_2_fu_658_p2);
    sensitive << ( bvh_d_index_11_reg_244 );

    SC_METHOD(thread_j_fu_492_p2);
    sensitive << ( bvh_d_index_4_reg_212 );

    SC_METHOD(thread_not_Result_s_fu_671_p2);
    sensitive << ( tmp_23_fu_664_p3 );

    SC_METHOD(thread_p_0289_2_i_fu_687_p3);
    sensitive << ( p_Result_13_reg_791 );
    sensitive << ( rem_next_V_reg_805 );
    sensitive << ( tmp_23_fu_664_p3 );

    SC_METHOD(thread_p_050_6_i_fu_427_p3);
    sensitive << ( sel_tmp2_fu_421_p2 );
    sensitive << ( p_Result_10_fu_387_p4 );
    sensitive << ( sel_tmp_fu_407_p3 );

    SC_METHOD(thread_p_Repl2_1_fu_478_p1);
    sensitive << ( tmp_17_fu_470_p3 );

    SC_METHOD(thread_p_Repl2_2_fu_584_p1);
    sensitive << ( tmp_20_fu_576_p3 );

    SC_METHOD(thread_p_Repl2_3_fu_644_p1);
    sensitive << ( tmp_25_fu_636_p3 );

    SC_METHOD(thread_p_Repl2_4_fu_303_p1);
    sensitive << ( tmp_2_fu_296_p3 );

    SC_METHOD(thread_p_Repl2_5_fu_723_p1);
    sensitive << ( tmp_12_fu_715_p3 );

    SC_METHOD(thread_p_Repl2_s_fu_383_p1);
    sensitive << ( tmp_7_fu_375_p3 );

    SC_METHOD(thread_p_Result_10_fu_387_p4);
    sensitive << ( p_Val2_s_reg_143 );
    sensitive << ( index_assign_cast_fu_361_p1 );
    sensitive << ( p_Repl2_s_fu_383_p1 );

    SC_METHOD(thread_p_Result_11_fu_397_p4);
    sensitive << ( p_Val2_s_reg_143 );
    sensitive << ( index_assign_cast_fu_361_p1 );

    SC_METHOD(thread_p_Result_12_fu_482_p4);
    sensitive << ( p_Val2_3_reg_202 );
    sensitive << ( index_assign_13_cast_fu_466_p1 );
    sensitive << ( p_Repl2_1_fu_478_p1 );

    SC_METHOD(thread_p_Result_13_fu_542_p5);
    sensitive << ( p_Val2_3_reg_202 );
    sensitive << ( tmp_6_fu_534_p3 );

    SC_METHOD(thread_p_Result_14_fu_588_p4);
    sensitive << ( p_Val2_4_fu_110 );
    sensitive << ( index_assign_17_cast_fu_572_p1 );
    sensitive << ( p_Repl2_2_fu_584_p1 );

    SC_METHOD(thread_p_Result_15_fu_648_p4);
    sensitive << ( p_Val2_6_reg_234 );
    sensitive << ( index_assign_19_cast_fu_632_p1 );
    sensitive << ( p_Repl2_3_fu_644_p1 );

    SC_METHOD(thread_p_Result_4_fu_727_p4);
    sensitive << ( p_Val2_7_reg_255 );
    sensitive << ( index_assign_21_cast_fu_699_p1 );
    sensitive << ( p_Repl2_5_fu_723_p1 );

    SC_METHOD(thread_p_Result_9_fu_339_p4);
    sensitive << ( p_Val2_s_reg_143 );

    SC_METHOD(thread_p_Result_s_fu_307_p4);
    sensitive << ( x_in_V_reg_120 );
    sensitive << ( index_assign_11_cast_fu_280_p1 );
    sensitive << ( p_Repl2_4_fu_303_p1 );

    SC_METHOD(thread_rem_next_V_fu_609_p2);
    sensitive << ( p_Result_13_reg_791 );
    sensitive << ( p_Val2_4_fu_110 );

    SC_METHOD(thread_sel_tmp1_fu_415_p2);
    sensitive << ( tmp_fu_333_p2 );

    SC_METHOD(thread_sel_tmp2_fu_421_p2);
    sensitive << ( tmp_1_fu_349_p2 );
    sensitive << ( sel_tmp1_fu_415_p2 );

    SC_METHOD(thread_sel_tmp_fu_407_p3);
    sensitive << ( tmp_fu_333_p2 );
    sensitive << ( p_Result_9_fu_339_p4 );
    sensitive << ( p_Result_11_fu_397_p4 );

    SC_METHOD(thread_sqrt_int_V_fu_677_p4);
    sensitive << ( p_Val2_6_reg_234 );
    sensitive << ( not_Result_s_fu_671_p2 );

    SC_METHOD(thread_tmp_10_fu_440_p3);
    sensitive << ( i2_0_i_reg_190 );

    SC_METHOD(thread_tmp_11_fu_452_p3);
    sensitive << ( bvh_d_index_4_reg_212 );

    SC_METHOD(thread_tmp_12_fu_715_p3);
    sensitive << ( data_x_outp_V_reg_166 );
    sensitive << ( index_assign_21_cast_fu_699_p1 );

    SC_METHOD(thread_tmp_15_fu_518_p3);
    sensitive << ( p_Val2_s_reg_143 );
    sensitive << ( index_assign_15_cast_fu_514_p1 );

    SC_METHOD(thread_tmp_16_fu_526_p3);
    sensitive << ( p_Val2_s_reg_143 );
    sensitive << ( index_assign_16_cast_fu_504_p1 );

    SC_METHOD(thread_tmp_17_fu_470_p3);
    sensitive << ( p_Val2_3_reg_202 );
    sensitive << ( index_assign_14_cast_fu_448_p1 );

    SC_METHOD(thread_tmp_19_fu_558_p3);
    sensitive << ( bvh_d_index_9_reg_223 );

    SC_METHOD(thread_tmp_1_fu_349_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_i_fu_321_p2 );
    sensitive << ( i1_0_i_reg_155 );

    SC_METHOD(thread_tmp_20_fu_576_p3);
    sensitive << ( data_x_outp_V_reg_166 );
    sensitive << ( index_assign_18_cast_fu_554_p1 );

    SC_METHOD(thread_tmp_22_fu_618_p3);
    sensitive << ( bvh_d_index_11_reg_244 );

    SC_METHOD(thread_tmp_23_fu_664_p3);
    sensitive << ( rem_next_V_reg_805 );

    SC_METHOD(thread_tmp_25_fu_636_p3);
    sensitive << ( p_Val2_6_reg_234 );
    sensitive << ( index_assign_20_cast_fu_614_p1 );

    SC_METHOD(thread_tmp_2_fu_296_p3);
    sensitive << ( inputData_in_V_read );
    sensitive << ( index_assign_11_cast_fu_280_p1 );

    SC_METHOD(thread_tmp_6_fu_534_p3);
    sensitive << ( tmp_15_fu_518_p3 );
    sensitive << ( tmp_16_fu_526_p3 );

    SC_METHOD(thread_tmp_7_fu_375_p3);
    sensitive << ( x_in_V_reg_120 );
    sensitive << ( index_assign_12_cast_fu_371_p1 );

    SC_METHOD(thread_tmp_fu_333_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_i_fu_321_p2 );
    sensitive << ( i1_0_i_reg_155 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_i3_fu_284_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_i_fu_321_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_11_fu_452_p3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_19_fu_558_p3 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_22_fu_618_p3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_i6_fu_703_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_10_fu_440_p3 );

    ap_CS_fsm = "00000001";
    ap_return_preg = "0000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cordic_base_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inputData_in_V_read, "(port)inputData_in_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, bit_fu_290_p2, "bit_fu_290_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, p_Result_s_fu_307_p4, "p_Result_s_fu_307_p4");
    sc_trace(mVcdFile, exitcond_i3_fu_284_p2, "exitcond_i3_fu_284_p2");
    sc_trace(mVcdFile, i_fu_327_p2, "i_fu_327_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, p_050_6_i_fu_427_p3, "p_050_6_i_fu_427_p3");
    sc_trace(mVcdFile, exitcond_i_fu_321_p2, "exitcond_i_fu_321_p2");
    sc_trace(mVcdFile, p_Result_12_fu_482_p4, "p_Result_12_fu_482_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_11_fu_452_p3, "tmp_11_fu_452_p3");
    sc_trace(mVcdFile, j_fu_492_p2, "j_fu_492_p2");
    sc_trace(mVcdFile, p_Result_13_fu_542_p5, "p_Result_13_fu_542_p5");
    sc_trace(mVcdFile, p_Result_13_reg_791, "p_Result_13_reg_791");
    sc_trace(mVcdFile, j_1_fu_598_p2, "j_1_fu_598_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_19_fu_558_p3, "tmp_19_fu_558_p3");
    sc_trace(mVcdFile, rem_next_V_fu_609_p2, "rem_next_V_fu_609_p2");
    sc_trace(mVcdFile, rem_next_V_reg_805, "rem_next_V_reg_805");
    sc_trace(mVcdFile, p_Result_15_fu_648_p4, "p_Result_15_fu_648_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_22_fu_618_p3, "tmp_22_fu_618_p3");
    sc_trace(mVcdFile, j_2_fu_658_p2, "j_2_fu_658_p2");
    sc_trace(mVcdFile, sqrt_int_V_fu_677_p4, "sqrt_int_V_fu_677_p4");
    sc_trace(mVcdFile, p_0289_2_i_fu_687_p3, "p_0289_2_i_fu_687_p3");
    sc_trace(mVcdFile, i_2_fu_693_p2, "i_2_fu_693_p2");
    sc_trace(mVcdFile, bit_1_fu_709_p2, "bit_1_fu_709_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, p_Result_4_fu_727_p4, "p_Result_4_fu_727_p4");
    sc_trace(mVcdFile, exitcond_i6_fu_703_p2, "exitcond_i6_fu_703_p2");
    sc_trace(mVcdFile, x_in_V_reg_120, "x_in_V_reg_120");
    sc_trace(mVcdFile, bvh_d_index_reg_132, "bvh_d_index_reg_132");
    sc_trace(mVcdFile, p_Val2_s_reg_143, "p_Val2_s_reg_143");
    sc_trace(mVcdFile, i1_0_i_reg_155, "i1_0_i_reg_155");
    sc_trace(mVcdFile, data_x_outp_V_reg_166, "data_x_outp_V_reg_166");
    sc_trace(mVcdFile, p_0289_0_i_reg_178, "p_0289_0_i_reg_178");
    sc_trace(mVcdFile, i2_0_i_reg_190, "i2_0_i_reg_190");
    sc_trace(mVcdFile, p_Val2_3_reg_202, "p_Val2_3_reg_202");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_10_fu_440_p3, "tmp_10_fu_440_p3");
    sc_trace(mVcdFile, bvh_d_index_4_reg_212, "bvh_d_index_4_reg_212");
    sc_trace(mVcdFile, bvh_d_index_9_reg_223, "bvh_d_index_9_reg_223");
    sc_trace(mVcdFile, p_Val2_6_reg_234, "p_Val2_6_reg_234");
    sc_trace(mVcdFile, bvh_d_index_11_reg_244, "bvh_d_index_11_reg_244");
    sc_trace(mVcdFile, p_Val2_7_reg_255, "p_Val2_7_reg_255");
    sc_trace(mVcdFile, bvh_d_index_6_reg_266, "bvh_d_index_6_reg_266");
    sc_trace(mVcdFile, p_Val2_4_fu_110, "p_Val2_4_fu_110");
    sc_trace(mVcdFile, p_Result_14_fu_588_p4, "p_Result_14_fu_588_p4");
    sc_trace(mVcdFile, index_assign_11_cast_fu_280_p1, "index_assign_11_cast_fu_280_p1");
    sc_trace(mVcdFile, tmp_2_fu_296_p3, "tmp_2_fu_296_p3");
    sc_trace(mVcdFile, p_Repl2_4_fu_303_p1, "p_Repl2_4_fu_303_p1");
    sc_trace(mVcdFile, bvh_d_index_1_fu_355_p2, "bvh_d_index_1_fu_355_p2");
    sc_trace(mVcdFile, i1_0_i_cast_fu_317_p1, "i1_0_i_cast_fu_317_p1");
    sc_trace(mVcdFile, bvh_d_index_2_fu_365_p2, "bvh_d_index_2_fu_365_p2");
    sc_trace(mVcdFile, index_assign_12_cast_fu_371_p1, "index_assign_12_cast_fu_371_p1");
    sc_trace(mVcdFile, tmp_7_fu_375_p3, "tmp_7_fu_375_p3");
    sc_trace(mVcdFile, index_assign_cast_fu_361_p1, "index_assign_cast_fu_361_p1");
    sc_trace(mVcdFile, p_Repl2_s_fu_383_p1, "p_Repl2_s_fu_383_p1");
    sc_trace(mVcdFile, tmp_fu_333_p2, "tmp_fu_333_p2");
    sc_trace(mVcdFile, p_Result_9_fu_339_p4, "p_Result_9_fu_339_p4");
    sc_trace(mVcdFile, p_Result_11_fu_397_p4, "p_Result_11_fu_397_p4");
    sc_trace(mVcdFile, tmp_1_fu_349_p2, "tmp_1_fu_349_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_415_p2, "sel_tmp1_fu_415_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_421_p2, "sel_tmp2_fu_421_p2");
    sc_trace(mVcdFile, p_Result_10_fu_387_p4, "p_Result_10_fu_387_p4");
    sc_trace(mVcdFile, sel_tmp_fu_407_p3, "sel_tmp_fu_407_p3");
    sc_trace(mVcdFile, bvh_d_index_3_fu_460_p2, "bvh_d_index_3_fu_460_p2");
    sc_trace(mVcdFile, index_assign_14_cast_fu_448_p1, "index_assign_14_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_17_fu_470_p3, "tmp_17_fu_470_p3");
    sc_trace(mVcdFile, index_assign_13_cast_fu_466_p1, "index_assign_13_cast_fu_466_p1");
    sc_trace(mVcdFile, p_Repl2_1_fu_478_p1, "p_Repl2_1_fu_478_p1");
    sc_trace(mVcdFile, bvh_d_index_7_fu_498_p2, "bvh_d_index_7_fu_498_p2");
    sc_trace(mVcdFile, bvh_d_index_5_fu_508_p2, "bvh_d_index_5_fu_508_p2");
    sc_trace(mVcdFile, index_assign_15_cast_fu_514_p1, "index_assign_15_cast_fu_514_p1");
    sc_trace(mVcdFile, index_assign_16_cast_fu_504_p1, "index_assign_16_cast_fu_504_p1");
    sc_trace(mVcdFile, tmp_15_fu_518_p3, "tmp_15_fu_518_p3");
    sc_trace(mVcdFile, tmp_16_fu_526_p3, "tmp_16_fu_526_p3");
    sc_trace(mVcdFile, tmp_6_fu_534_p3, "tmp_6_fu_534_p3");
    sc_trace(mVcdFile, bvh_d_index_8_fu_566_p2, "bvh_d_index_8_fu_566_p2");
    sc_trace(mVcdFile, index_assign_18_cast_fu_554_p1, "index_assign_18_cast_fu_554_p1");
    sc_trace(mVcdFile, tmp_20_fu_576_p3, "tmp_20_fu_576_p3");
    sc_trace(mVcdFile, index_assign_17_cast_fu_572_p1, "index_assign_17_cast_fu_572_p1");
    sc_trace(mVcdFile, p_Repl2_2_fu_584_p1, "p_Repl2_2_fu_584_p1");
    sc_trace(mVcdFile, bvh_d_index_10_fu_626_p2, "bvh_d_index_10_fu_626_p2");
    sc_trace(mVcdFile, index_assign_20_cast_fu_614_p1, "index_assign_20_cast_fu_614_p1");
    sc_trace(mVcdFile, tmp_25_fu_636_p3, "tmp_25_fu_636_p3");
    sc_trace(mVcdFile, index_assign_19_cast_fu_632_p1, "index_assign_19_cast_fu_632_p1");
    sc_trace(mVcdFile, p_Repl2_3_fu_644_p1, "p_Repl2_3_fu_644_p1");
    sc_trace(mVcdFile, tmp_23_fu_664_p3, "tmp_23_fu_664_p3");
    sc_trace(mVcdFile, not_Result_s_fu_671_p2, "not_Result_s_fu_671_p2");
    sc_trace(mVcdFile, index_assign_21_cast_fu_699_p1, "index_assign_21_cast_fu_699_p1");
    sc_trace(mVcdFile, tmp_12_fu_715_p3, "tmp_12_fu_715_p3");
    sc_trace(mVcdFile, p_Repl2_5_fu_723_p1, "p_Repl2_5_fu_723_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cordic_base::~cordic_base() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void cordic_base::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv25_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i6_fu_703_p2.read()))) {
            ap_return_preg = p_Val2_7_reg_255.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_618_p3.read()))) {
        bvh_d_index_11_reg_244 = j_2_fu_658_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_558_p3.read()))) {
        bvh_d_index_11_reg_244 = ap_const_lv6_17;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_452_p3.read()))) {
        bvh_d_index_4_reg_212 = j_fu_492_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_10_fu_440_p3.read()))) {
        bvh_d_index_4_reg_212 = ap_const_lv6_17;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_10_fu_440_p3.read()))) {
        bvh_d_index_6_reg_266 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i6_fu_703_p2.read()))) {
        bvh_d_index_6_reg_266 = bit_1_fu_709_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_558_p3.read()))) {
        bvh_d_index_9_reg_223 = j_1_fu_598_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(tmp_11_fu_452_p3.read(), ap_const_lv1_1))) {
        bvh_d_index_9_reg_223 = ap_const_lv6_16;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_i3_fu_284_p2.read(), ap_const_lv1_0))) {
        bvh_d_index_reg_132 = bit_fu_290_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        bvh_d_index_reg_132 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_321_p2.read(), ap_const_lv1_1))) {
        data_x_outp_V_reg_166 = ap_const_lv25_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_22_fu_618_p3.read()))) {
        data_x_outp_V_reg_166 = sqrt_int_V_fu_677_p4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_i3_fu_284_p2.read(), ap_const_lv1_1))) {
        i1_0_i_reg_155 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_321_p2.read()))) {
        i1_0_i_reg_155 = i_fu_327_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_321_p2.read(), ap_const_lv1_1))) {
        i2_0_i_reg_190 = ap_const_lv6_18;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_22_fu_618_p3.read()))) {
        i2_0_i_reg_190 = i_2_fu_693_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_321_p2.read(), ap_const_lv1_1))) {
        p_0289_0_i_reg_178 = ap_const_lv50_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_22_fu_618_p3.read()))) {
        p_0289_0_i_reg_178 = p_0289_2_i_fu_687_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_452_p3.read()))) {
        p_Val2_3_reg_202 = p_Result_12_fu_482_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_10_fu_440_p3.read()))) {
        p_Val2_3_reg_202 = p_0289_0_i_reg_178.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_558_p3.read()))) {
        p_Val2_4_fu_110 = p_Result_14_fu_588_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(exitcond_i_fu_321_p2.read(), ap_const_lv1_1))) {
        p_Val2_4_fu_110 = ap_const_lv50_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_618_p3.read()))) {
        p_Val2_6_reg_234 = p_Result_15_fu_648_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_558_p3.read()))) {
        p_Val2_6_reg_234 = data_x_outp_V_reg_166.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_11_fu_452_p3.read(), ap_const_lv1_1))) {
        p_Result_13_reg_791 = p_Result_13_fu_542_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i6_fu_703_p2.read()))) {
        p_Val2_7_reg_255 = p_Result_4_fu_727_p4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_321_p2.read()))) {
        p_Val2_s_reg_143 = p_050_6_i_fu_427_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_558_p3.read()))) {
        rem_next_V_reg_805 = rem_next_V_fu_609_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_i3_fu_284_p2.read(), ap_const_lv1_0))) {
        x_in_V_reg_120 = p_Result_s_fu_307_p4.read();
    }
}

void cordic_base::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cordic_base::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cordic_base::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cordic_base::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cordic_base::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cordic_base::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cordic_base::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void cordic_base::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void cordic_base::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i6_fu_703_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cordic_base::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cordic_base::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i6_fu_703_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cordic_base::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i6_fu_703_p2.read()))) {
        ap_return = p_Val2_7_reg_255.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void cordic_base::thread_bit_1_fu_709_p2() {
    bit_1_fu_709_p2 = (!bvh_d_index_6_reg_266.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(bvh_d_index_6_reg_266.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void cordic_base::thread_bit_fu_290_p2() {
    bit_fu_290_p2 = (!bvh_d_index_reg_132.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_reg_132.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cordic_base::thread_bvh_d_index_10_fu_626_p2() {
    bvh_d_index_10_fu_626_p2 = (!bvh_d_index_11_reg_244.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_11_reg_244.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cordic_base::thread_bvh_d_index_1_fu_355_p2() {
    bvh_d_index_1_fu_355_p2 = (!ap_const_lv6_31.is_01() || !i1_0_i_reg_155.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_31) - sc_biguint<6>(i1_0_i_reg_155.read()));
}

void cordic_base::thread_bvh_d_index_2_fu_365_p2() {
    bvh_d_index_2_fu_365_p2 = (!ap_const_lv7_30.is_01() || !i1_0_i_cast_fu_317_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_30) - sc_biguint<7>(i1_0_i_cast_fu_317_p1.read()));
}

void cordic_base::thread_bvh_d_index_3_fu_460_p2() {
    bvh_d_index_3_fu_460_p2 = (!bvh_d_index_4_reg_212.read().is_01() || !ap_const_lv6_2.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_4_reg_212.read()) + sc_biguint<6>(ap_const_lv6_2));
}

void cordic_base::thread_bvh_d_index_5_fu_508_p2() {
    bvh_d_index_5_fu_508_p2 = (bvh_d_index_7_fu_498_p2.read() | ap_const_lv6_1);
}

void cordic_base::thread_bvh_d_index_7_fu_498_p2() {
    bvh_d_index_7_fu_498_p2 = (!ap_const_lv6_1.is_01())? sc_lv<6>(): i2_0_i_reg_190.read() << (unsigned short)ap_const_lv6_1.to_uint();
}

void cordic_base::thread_bvh_d_index_8_fu_566_p2() {
    bvh_d_index_8_fu_566_p2 = (!bvh_d_index_9_reg_223.read().is_01() || !ap_const_lv6_2.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_9_reg_223.read()) + sc_biguint<6>(ap_const_lv6_2));
}

void cordic_base::thread_exitcond_i3_fu_284_p2() {
    exitcond_i3_fu_284_p2 = (!bvh_d_index_reg_132.read().is_01() || !ap_const_lv6_30.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_reg_132.read() == ap_const_lv6_30);
}

void cordic_base::thread_exitcond_i6_fu_703_p2() {
    exitcond_i6_fu_703_p2 = (!bvh_d_index_6_reg_266.read().is_01() || !ap_const_lv5_19.is_01())? sc_lv<1>(): sc_lv<1>(bvh_d_index_6_reg_266.read() == ap_const_lv5_19);
}

void cordic_base::thread_exitcond_i_fu_321_p2() {
    exitcond_i_fu_321_p2 = (!i1_0_i_reg_155.read().is_01() || !ap_const_lv6_32.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_i_reg_155.read() == ap_const_lv6_32);
}

void cordic_base::thread_i1_0_i_cast_fu_317_p1() {
    i1_0_i_cast_fu_317_p1 = esl_zext<7,6>(i1_0_i_reg_155.read());
}

void cordic_base::thread_i_2_fu_693_p2() {
    i_2_fu_693_p2 = (!i2_0_i_reg_190.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(i2_0_i_reg_190.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void cordic_base::thread_i_fu_327_p2() {
    i_fu_327_p2 = (!i1_0_i_reg_155.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i1_0_i_reg_155.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cordic_base::thread_index_assign_11_cast_fu_280_p1() {
    index_assign_11_cast_fu_280_p1 = esl_zext<32,6>(bvh_d_index_reg_132.read());
}

void cordic_base::thread_index_assign_12_cast_fu_371_p1() {
    index_assign_12_cast_fu_371_p1 = esl_sext<32,7>(bvh_d_index_2_fu_365_p2.read());
}

void cordic_base::thread_index_assign_13_cast_fu_466_p1() {
    index_assign_13_cast_fu_466_p1 = esl_zext<32,6>(bvh_d_index_3_fu_460_p2.read());
}

void cordic_base::thread_index_assign_14_cast_fu_448_p1() {
    index_assign_14_cast_fu_448_p1 = esl_sext<32,6>(bvh_d_index_4_reg_212.read());
}

void cordic_base::thread_index_assign_15_cast_fu_514_p1() {
    index_assign_15_cast_fu_514_p1 = esl_zext<32,6>(bvh_d_index_5_fu_508_p2.read());
}

void cordic_base::thread_index_assign_16_cast_fu_504_p1() {
    index_assign_16_cast_fu_504_p1 = esl_zext<32,6>(bvh_d_index_7_fu_498_p2.read());
}

void cordic_base::thread_index_assign_17_cast_fu_572_p1() {
    index_assign_17_cast_fu_572_p1 = esl_zext<32,6>(bvh_d_index_8_fu_566_p2.read());
}

void cordic_base::thread_index_assign_18_cast_fu_554_p1() {
    index_assign_18_cast_fu_554_p1 = esl_sext<32,6>(bvh_d_index_9_reg_223.read());
}

void cordic_base::thread_index_assign_19_cast_fu_632_p1() {
    index_assign_19_cast_fu_632_p1 = esl_zext<32,6>(bvh_d_index_10_fu_626_p2.read());
}

void cordic_base::thread_index_assign_20_cast_fu_614_p1() {
    index_assign_20_cast_fu_614_p1 = esl_sext<32,6>(bvh_d_index_11_reg_244.read());
}

void cordic_base::thread_index_assign_21_cast_fu_699_p1() {
    index_assign_21_cast_fu_699_p1 = esl_zext<32,5>(bvh_d_index_6_reg_266.read());
}

void cordic_base::thread_index_assign_cast_fu_361_p1() {
    index_assign_cast_fu_361_p1 = esl_zext<32,6>(bvh_d_index_1_fu_355_p2.read());
}

void cordic_base::thread_j_1_fu_598_p2() {
    j_1_fu_598_p2 = (!bvh_d_index_9_reg_223.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_9_reg_223.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void cordic_base::thread_j_2_fu_658_p2() {
    j_2_fu_658_p2 = (!bvh_d_index_11_reg_244.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_11_reg_244.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void cordic_base::thread_j_fu_492_p2() {
    j_fu_492_p2 = (!bvh_d_index_4_reg_212.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(bvh_d_index_4_reg_212.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void cordic_base::thread_not_Result_s_fu_671_p2() {
    not_Result_s_fu_671_p2 = (tmp_23_fu_664_p3.read() ^ ap_const_lv1_1);
}

void cordic_base::thread_p_0289_2_i_fu_687_p3() {
    p_0289_2_i_fu_687_p3 = (!tmp_23_fu_664_p3.read()[0].is_01())? sc_lv<50>(): ((tmp_23_fu_664_p3.read()[0].to_bool())? p_Result_13_reg_791.read(): rem_next_V_reg_805.read());
}

void cordic_base::thread_p_050_6_i_fu_427_p3() {
    p_050_6_i_fu_427_p3 = (!sel_tmp2_fu_421_p2.read()[0].is_01())? sc_lv<50>(): ((sel_tmp2_fu_421_p2.read()[0].to_bool())? p_Result_10_fu_387_p4.read(): sel_tmp_fu_407_p3.read());
}

void cordic_base::thread_p_Repl2_1_fu_478_p1() {
    p_Repl2_1_fu_478_p1 = esl_zext<64,1>(tmp_17_fu_470_p3.read());
}

void cordic_base::thread_p_Repl2_2_fu_584_p1() {
    p_Repl2_2_fu_584_p1 = esl_zext<64,1>(tmp_20_fu_576_p3.read());
}

void cordic_base::thread_p_Repl2_3_fu_644_p1() {
    p_Repl2_3_fu_644_p1 = esl_zext<64,1>(tmp_25_fu_636_p3.read());
}

void cordic_base::thread_p_Repl2_4_fu_303_p1() {
    p_Repl2_4_fu_303_p1 = esl_zext<64,1>(tmp_2_fu_296_p3.read());
}

void cordic_base::thread_p_Repl2_5_fu_723_p1() {
    p_Repl2_5_fu_723_p1 = esl_zext<64,1>(tmp_12_fu_715_p3.read());
}

void cordic_base::thread_p_Repl2_s_fu_383_p1() {
    p_Repl2_s_fu_383_p1 = esl_zext<64,1>(tmp_7_fu_375_p3.read());
}

void cordic_base::thread_p_Result_10_fu_387_p4() {
    p_Result_10_fu_387_p4 = esl_bitset<50,50,32,64>(p_Val2_s_reg_143.read(), index_assign_cast_fu_361_p1.read(), p_Repl2_s_fu_383_p1.read());
}

void cordic_base::thread_p_Result_11_fu_397_p4() {
    p_Result_11_fu_397_p4 = esl_bitset<50,50,32,64>(p_Val2_s_reg_143.read(), index_assign_cast_fu_361_p1.read(), ap_const_lv64_0);
}

void cordic_base::thread_p_Result_12_fu_482_p4() {
    p_Result_12_fu_482_p4 = esl_bitset<50,50,32,64>(p_Val2_3_reg_202.read(), index_assign_13_cast_fu_466_p1.read(), p_Repl2_1_fu_478_p1.read());
}

void cordic_base::thread_p_Result_13_fu_542_p5() {
    p_Result_13_fu_542_p5 = esl_partset<50,50,2,32,32>(p_Val2_3_reg_202.read(), tmp_6_fu_534_p3.read(), ap_const_lv32_0, ap_const_lv32_1);
}

void cordic_base::thread_p_Result_14_fu_588_p4() {
    p_Result_14_fu_588_p4 = esl_bitset<50,50,32,64>(p_Val2_4_fu_110.read(), index_assign_17_cast_fu_572_p1.read(), p_Repl2_2_fu_584_p1.read());
}

void cordic_base::thread_p_Result_15_fu_648_p4() {
    p_Result_15_fu_648_p4 = esl_bitset<25,25,32,64>(p_Val2_6_reg_234.read(), index_assign_19_cast_fu_632_p1.read(), p_Repl2_3_fu_644_p1.read());
}

void cordic_base::thread_p_Result_4_fu_727_p4() {
    p_Result_4_fu_727_p4 = esl_bitset<25,25,32,64>(p_Val2_7_reg_255.read(), index_assign_21_cast_fu_699_p1.read(), p_Repl2_5_fu_723_p1.read());
}

void cordic_base::thread_p_Result_9_fu_339_p4() {
    p_Result_9_fu_339_p4 = esl_bitset<50,50,32,1>(p_Val2_s_reg_143.read(), ap_const_lv32_31, ap_const_lv1_0);
}

void cordic_base::thread_p_Result_s_fu_307_p4() {
    p_Result_s_fu_307_p4 = esl_bitset<48,48,32,64>(x_in_V_reg_120.read(), index_assign_11_cast_fu_280_p1.read(), p_Repl2_4_fu_303_p1.read());
}

void cordic_base::thread_rem_next_V_fu_609_p2() {
    rem_next_V_fu_609_p2 = (!p_Result_13_reg_791.read().is_01() || !p_Val2_4_fu_110.read().is_01())? sc_lv<50>(): (sc_biguint<50>(p_Result_13_reg_791.read()) - sc_biguint<50>(p_Val2_4_fu_110.read()));
}

void cordic_base::thread_sel_tmp1_fu_415_p2() {
    sel_tmp1_fu_415_p2 = (tmp_fu_333_p2.read() ^ ap_const_lv1_1);
}

void cordic_base::thread_sel_tmp2_fu_421_p2() {
    sel_tmp2_fu_421_p2 = (tmp_1_fu_349_p2.read() & sel_tmp1_fu_415_p2.read());
}

void cordic_base::thread_sel_tmp_fu_407_p3() {
    sel_tmp_fu_407_p3 = (!tmp_fu_333_p2.read()[0].is_01())? sc_lv<50>(): ((tmp_fu_333_p2.read()[0].to_bool())? p_Result_9_fu_339_p4.read(): p_Result_11_fu_397_p4.read());
}

void cordic_base::thread_sqrt_int_V_fu_677_p4() {
    sqrt_int_V_fu_677_p4 = esl_bitset<25,25,32,1>(p_Val2_6_reg_234.read(), ap_const_lv32_0, not_Result_s_fu_671_p2.read());
}

void cordic_base::thread_tmp_10_fu_440_p3() {
    tmp_10_fu_440_p3 = i2_0_i_reg_190.read().range(5, 5);
}

void cordic_base::thread_tmp_11_fu_452_p3() {
    tmp_11_fu_452_p3 = bvh_d_index_4_reg_212.read().range(5, 5);
}

void cordic_base::thread_tmp_12_fu_715_p3() {
    tmp_12_fu_715_p3 = (!index_assign_21_cast_fu_699_p1.read().is_01() || sc_biguint<32>(index_assign_21_cast_fu_699_p1.read()).to_uint() >= 25)? sc_lv<1>(): data_x_outp_V_reg_166.read().range(sc_biguint<32>(index_assign_21_cast_fu_699_p1.read()).to_uint(), sc_biguint<32>(index_assign_21_cast_fu_699_p1.read()).to_uint());
}

void cordic_base::thread_tmp_15_fu_518_p3() {
    tmp_15_fu_518_p3 = (!index_assign_15_cast_fu_514_p1.read().is_01() || sc_biguint<32>(index_assign_15_cast_fu_514_p1.read()).to_uint() >= 50)? sc_lv<1>(): p_Val2_s_reg_143.read().range(sc_biguint<32>(index_assign_15_cast_fu_514_p1.read()).to_uint(), sc_biguint<32>(index_assign_15_cast_fu_514_p1.read()).to_uint());
}

void cordic_base::thread_tmp_16_fu_526_p3() {
    tmp_16_fu_526_p3 = (!index_assign_16_cast_fu_504_p1.read().is_01() || sc_biguint<32>(index_assign_16_cast_fu_504_p1.read()).to_uint() >= 50)? sc_lv<1>(): p_Val2_s_reg_143.read().range(sc_biguint<32>(index_assign_16_cast_fu_504_p1.read()).to_uint(), sc_biguint<32>(index_assign_16_cast_fu_504_p1.read()).to_uint());
}

void cordic_base::thread_tmp_17_fu_470_p3() {
    tmp_17_fu_470_p3 = (!index_assign_14_cast_fu_448_p1.read().is_01() || sc_biguint<32>(index_assign_14_cast_fu_448_p1.read()).to_uint() >= 50)? sc_lv<1>(): p_Val2_3_reg_202.read().range(sc_biguint<32>(index_assign_14_cast_fu_448_p1.read()).to_uint(), sc_biguint<32>(index_assign_14_cast_fu_448_p1.read()).to_uint());
}

void cordic_base::thread_tmp_19_fu_558_p3() {
    tmp_19_fu_558_p3 = bvh_d_index_9_reg_223.read().range(5, 5);
}

void cordic_base::thread_tmp_1_fu_349_p2() {
    tmp_1_fu_349_p2 = (!i1_0_i_reg_155.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): (sc_biguint<6>(i1_0_i_reg_155.read()) < sc_biguint<6>(ap_const_lv6_31));
}

void cordic_base::thread_tmp_20_fu_576_p3() {
    tmp_20_fu_576_p3 = (!index_assign_18_cast_fu_554_p1.read().is_01() || sc_biguint<32>(index_assign_18_cast_fu_554_p1.read()).to_uint() >= 25)? sc_lv<1>(): data_x_outp_V_reg_166.read().range(sc_biguint<32>(index_assign_18_cast_fu_554_p1.read()).to_uint(), sc_biguint<32>(index_assign_18_cast_fu_554_p1.read()).to_uint());
}

void cordic_base::thread_tmp_22_fu_618_p3() {
    tmp_22_fu_618_p3 = bvh_d_index_11_reg_244.read().range(5, 5);
}

void cordic_base::thread_tmp_23_fu_664_p3() {
    tmp_23_fu_664_p3 = rem_next_V_reg_805.read().range(25, 25);
}

void cordic_base::thread_tmp_25_fu_636_p3() {
    tmp_25_fu_636_p3 = (!index_assign_20_cast_fu_614_p1.read().is_01() || sc_biguint<32>(index_assign_20_cast_fu_614_p1.read()).to_uint() >= 25)? sc_lv<1>(): p_Val2_6_reg_234.read().range(sc_biguint<32>(index_assign_20_cast_fu_614_p1.read()).to_uint(), sc_biguint<32>(index_assign_20_cast_fu_614_p1.read()).to_uint());
}

void cordic_base::thread_tmp_2_fu_296_p3() {
    tmp_2_fu_296_p3 = (!index_assign_11_cast_fu_280_p1.read().is_01() || sc_biguint<32>(index_assign_11_cast_fu_280_p1.read()).to_uint() >= 48)? sc_lv<1>(): inputData_in_V_read.read().range(sc_biguint<32>(index_assign_11_cast_fu_280_p1.read()).to_uint(), sc_biguint<32>(index_assign_11_cast_fu_280_p1.read()).to_uint());
}

void cordic_base::thread_tmp_6_fu_534_p3() {
    tmp_6_fu_534_p3 = esl_concat<1,1>(tmp_15_fu_518_p3.read(), tmp_16_fu_526_p3.read());
}

void cordic_base::thread_tmp_7_fu_375_p3() {
    tmp_7_fu_375_p3 = (!index_assign_12_cast_fu_371_p1.read().is_01() || sc_biguint<32>(index_assign_12_cast_fu_371_p1.read()).to_uint() >= 48)? sc_lv<1>(): x_in_V_reg_120.read().range(sc_biguint<32>(index_assign_12_cast_fu_371_p1.read()).to_uint(), sc_biguint<32>(index_assign_12_cast_fu_371_p1.read()).to_uint());
}

void cordic_base::thread_tmp_fu_333_p2() {
    tmp_fu_333_p2 = (!i1_0_i_reg_155.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_i_reg_155.read() == ap_const_lv6_0);
}

void cordic_base::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_i3_fu_284_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_i_fu_321_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_10_fu_440_p3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_11_fu_452_p3.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_19_fu_558_p3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_22_fu_618_p3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_i6_fu_703_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

